services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./eng/desafio-verity-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_DB=${KEYCLOAK_DB}
      - KEYCLOAK_DB_URL=jdbc:postgresql://keycloak_db:5432/${KEYCLOAK_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - DESAFIO_VERITY_WEBAPI_SECRET=${DESAFIO_VERITY_WEBAPI_SECRET}
    ports:
      - '8080:8080'
    depends_on:
      keycloak_db:
        condition: service_healthy
        restart: true

  keycloak_db:
    image: postgres:17.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${KEYCLOAK_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${KEYCLOAK_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - '5432:5432'

  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    restart: unless-stopped
    command: 
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:7.4
    restart: unless-stopped
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4.1-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'

volumes:
  postgres_data: {}
  mongodb_data: {}
  redis_data: {}
  rabbitmq_data: {}