name: .NET Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./components/service/

    - name: Lint
      run: dotnet format --no-restore --verify-no-changes --verbosity normal
      working-directory: ./components/service/

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./components/service/

    - name: Test
      run: dotnet test --no-build --list-tests --verbosity normal
      working-directory: ./components/service/
