name: Angular UI CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ui.yml'
      - 'components/ui/**/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ui.yml'
      - 'components/ui/**/*'

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./components/ui/fluxo-caixa/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./components/ui/fluxo-caixa

      - name: Lint
        run: npm run lint
        working-directory: ./components/ui/fluxo-caixa

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./components/ui/fluxo-caixa/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./components/ui/fluxo-caixa

      - name: Build development
        run: npm run build
        working-directory: ./components/ui/fluxo-caixa

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./components/ui/fluxo-caixa/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./components/ui/fluxo-caixa

      - name: Run Tests
        run: npm run test:ci
        working-directory: ./components/ui/fluxo-caixa

  
